# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: terraform-provider-vagrant
builds:
  - binary: '{{ .ProjectName }}_{{ .Version }}'
    flags:
      - -trimpath
    goarch:
      - '386'
      - amd64
      - arm
      - arm64
    goos:
      - darwin
      - freebsd
      - linux
      - windows
    ignore:
      - goarch: '386'
        goos: darwin
    ldflags:
      - -s -w -X version.ProviderVersion={{.Version}}
    mod_timestamp: '{{ .CommitTimestamp }}'
archives:
  - name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    format: zip
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
env:
  - CGO_ENABLED=0
